# Generated by Django 4.1.7 on 2023-04-13 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0004_alter_medicine_amount_alter_medicine_end_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medicine',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='provider',
            options={'ordering': ('id',)},
        ),
    ]
