# Generated by Django 4.1.7 on 2023-04-13 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0005_alter_medicine_options_alter_provider_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='provider',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='provider', to='providers.provider', verbose_name='Поставщик'),
        ),
    ]
