# Generated by Django 4.1.7 on 2023-02-24 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashiers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashiers',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
