# Generated by Django 4.1.7 on 2023-02-25 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashiers', '0003_cashiers_user_alter_accounts_login_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='login',
            field=models.CharField(max_length=50, unique=True, verbose_name='Логин'),
        ),
        migrations.AlterField(
            model_name='cashiers',
            name='address',
            field=models.CharField(max_length=250, verbose_name='Адрес'),
        ),
    ]
