# Generated by Django 4.1.7 on 2023-04-13 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cashiers', '0008_alter_accounts_cashiers_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cashiers',
            options={'ordering': ('id',)},
        ),
        migrations.AlterField(
            model_name='accounts',
            name='cashiers_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cashiers_id', to='cashiers.cashiers', verbose_name='Кассир'),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='password',
            field=models.CharField(max_length=250, verbose_name='Пароль'),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='username',
            field=models.CharField(max_length=250, unique=True, verbose_name='Логин'),
        ),
    ]
